name: dgmentorp1_clone
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  provider: ^6.1.5
  audioplayers: ^6.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/app_icon.png" 


flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_icon.png
    - assets/images/slider_image.png
    - assets/app_icon.png
    - assets/images/course1_image.png
    - assets/images/course2_image.png
    - assets/images/playbook1_image.png
    - assets/images/playbook2_image.png
    - assets/images/course1_module1_image.png
    - assets/images/course1_module2_image.png